// Daftar lengkap 239 Qari dari mp3quran.net
export interface Qari {
  id: number;
  name: string;
  slug: string;
  status: string;
  rewayaIds: string;
  page: string;
  downloads: string;
}

export const MUROTAL_LIST: Qari[] = [
  { id: 1, name: "Abdelaziz sheim", slug: "aabd-laazyz-shym", status: "16 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/aabd-laazyz-shym", downloads: "https://www.mp3quran.net/id/aabd-laazyz-shym/downloads" },
  { id: 2, name: "Abdelmoujib Benkirane", slug: "aabd-lmgyb-bnkyr-n", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/aabd-lmgyb-bnkyr-n", downloads: "https://www.mp3quran.net/id/aabd-lmgyb-bnkyr-n/downloads" },
  { id: 3, name: "Abdllah khayyath", slug: "kyat", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/kyat", downloads: "https://www.mp3quran.net/id/kyat/downloads" },
  { id: 4, name: "Abdul Rahman bin Abdul Razzaq Al Badr", slug: "aabd-lrhmn-bn-aabd-lrz-k-lbdr", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/aabd-lrhmn-bn-aabd-lrz-k-lbdr", downloads: "https://www.mp3quran.net/id/aabd-lrhmn-bn-aabd-lrz-k-lbdr/downloads" },
  { id: 5, name: "Abdul basith abdul shamad", slug: "basit", status: "Al-Qur'an Lengkap", rewayaIds: "22,2,1", page: "https://www.mp3quran.net/id/basit", downloads: "https://www.mp3quran.net/id/basit/downloads" },
  { id: 6, name: "Abdul rahman as sudais", slug: "sds", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/sds", downloads: "https://www.mp3quran.net/id/sds/downloads" },
  { id: 7, name: "Abdul rasyid shufi", slug: "soufi", status: "Al-Qur'an Lengkap", rewayaIds: "3,7,1", page: "https://www.mp3quran.net/id/soufi", downloads: "https://www.mp3quran.net/id/soufi/downloads" },
  { id: 8, name: "Mahir al mu'aiqiliy", slug: "maher", status: "Al-Qur'an Lengkap", rewayaIds: "1,21,22", page: "https://www.mp3quran.net/id/maher", downloads: "https://www.mp3quran.net/id/maher/downloads" },
  { id: 9, name: "Mahmud khalil al hushariy", slug: "husr", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2,13,5", page: "https://www.mp3quran.net/id/husr", downloads: "https://www.mp3quran.net/id/husr/downloads" },
  { id: 10, name: "Muhammad shiddiq al minsyawiy", slug: "minsh", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,21", page: "https://www.mp3quran.net/id/minsh", downloads: "https://www.mp3quran.net/id/minsh/downloads" },
  { id: 11, name: "Musyari al afasiy", slug: "afs", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/afs", downloads: "https://www.mp3quran.net/id/afs/downloads" },
  { id: 12, name: "Saud as shuraim", slug: "shur", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/shur", downloads: "https://www.mp3quran.net/id/shur/downloads" },
  { id: 13, name: "Shaik abu bakr asy syathiriy", slug: "shatri", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/shatri", downloads: "https://www.mp3quran.net/id/shatri/downloads" },
  { id: 14, name: "Yasir ad duuisiry", slug: "yasser", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/yasser", downloads: "https://www.mp3quran.net/id/yasser/downloads" },
  { id: 15, name: "Abdullah al mathrud", slug: "mtrod", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/mtrod", downloads: "https://www.mp3quran.net/id/mtrod/downloads" },
  { id: 16, name: "Abdullah bin awwad al juhani", slug: "jhn", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/jhn", downloads: "https://www.mp3quran.net/id/jhn/downloads" },
  { id: 17, name: "Abdullah kamil", slug: "kamel", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/kamel", downloads: "https://www.mp3quran.net/id/kamel/downloads" },
  { id: 18, name: "Abdullaah khashm al mazrooy", slug: "mzroa", status: "14 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/mzroa", downloads: "https://www.mp3quran.net/id/mzroa/downloads" },
  { id: 19, name: "Abdulmuhsin al qasim", slug: "qasm", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/qasm", downloads: "https://www.mp3quran.net/id/qasm/downloads" },
  { id: 20, name: "Abdulmuhsin bin salih al qasim", slug: "abdulmohsen-alqasem", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdulmohsen-alqasem", downloads: "https://www.mp3quran.net/id/abdulmohsen-alqasem/downloads" },
  { id: 21, name: "Abdulmunim abdulmubdi", slug: "moneim", status: "Al-Qur'an Lengkap", rewayaIds: "1,22", page: "https://www.mp3quran.net/id/moneim", downloads: "https://www.mp3quran.net/id/moneim/downloads" },
  { id: 22, name: "Abdulwadood haneef", slug: "haneef", status: "15 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/haneef", downloads: "https://www.mp3quran.net/id/haneef/downloads" },
  { id: 23, name: "Ahmed al ajami", slug: "ahmed_aajmy", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/ahmed_aajmy", downloads: "https://www.mp3quran.net/id/ahmed_aajmy/downloads" },
  { id: 24, name: "Ahmed al hawashiy", slug: "hawashi", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/hawashi", downloads: "https://www.mp3quran.net/id/hawashi/downloads" },
  { id: 25, name: "Ahmed bin ali al ajmi", slug: "ajm", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/ajm", downloads: "https://www.mp3quran.net/id/ajm/downloads" },
  { id: 26, name: "Ahmed ibn abd al aziz al humaid", slug: "ahmed-ibn-abd-al-aziz-al-humaid", status: "15 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/ahmed-ibn-abd-al-aziz-al-humaid", downloads: "https://www.mp3quran.net/id/ahmed-ibn-abd-al-aziz-al-humaid/downloads" },
  { id: 27, name: "Ahmed neana", slug: "neana", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/neana", downloads: "https://www.mp3quran.net/id/neana/downloads" },
  { id: 28, name: "Akram alalaqimiy", slug: "akram", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/akram", downloads: "https://www.mp3quran.net/id/akram/downloads" },
  { id: 29, name: "Ali abd ar rahman al hudhaify", slug: "hthfi", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/hthfi", downloads: "https://www.mp3quran.net/id/hthfi/downloads" },
  { id: 30, name: "Ali bin abdulrahman alhuthaifi", slug: "ali", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ali", downloads: "https://www.mp3quran.net/id/ali/downloads" },
  { id: 31, name: "Ali hajjaj suesy", slug: "swsah", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/swsah", downloads: "https://www.mp3quran.net/id/swsah/downloads" },
  { id: 32, name: "Ali jaber", slug: "jabir", status: "Al-Qur'an Lengkap", rewayaIds: "1,2", page: "https://www.mp3quran.net/id/jabir", downloads: "https://www.mp3quran.net/id/jabir/downloads" },
  { id: 33, name: "Ayman suweyd", slug: "ayman", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ayman", downloads: "https://www.mp3quran.net/id/ayman/downloads" },
  { id: 34, name: "Aziz alili", slug: "alili", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/alili", downloads: "https://www.mp3quran.net/id/alili/downloads" },
  { id: 35, name: "Bandar baleelah", slug: "bandar", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/bandar", downloads: "https://www.mp3quran.net/id/bandar/downloads" },
  { id: 36, name: "Faris abbad", slug: "frs", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/frs", downloads: "https://www.mp3quran.net/id/frs/downloads" },
  { id: 37, name: "Hamad sinan", slug: "hamad-sinan", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/hamad-sinan", downloads: "https://www.mp3quran.net/id/hamad-sinan/downloads" },
  { id: 38, name: "Hamdy saad", slug: "hamdy-saad", status: "6 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/hamdy-saad", downloads: "https://www.mp3quran.net/id/hamdy-saad/downloads" },
  { id: 39, name: "Hani ar rifai", slug: "hani", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/hani", downloads: "https://www.mp3quran.net/id/hani/downloads" },
  { id: 40, name: "Husain al shaikh", slug: "husain_alshaikh", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/husain_alshaikh", downloads: "https://www.mp3quran.net/id/husain_alshaikh/downloads" },
  { id: 41, name: "Hussary mujawwad from egypt", slug: "husr-muj", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/husr-muj", downloads: "https://www.mp3quran.net/id/husr-muj/downloads" },
  { id: 42, name: "Ibrahim al akhdar", slug: "akdr", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2,8", page: "https://www.mp3quran.net/id/akdr", downloads: "https://www.mp3quran.net/id/akdr/downloads" },
  { id: 43, name: "Ibrahim al dosary", slug: "dos", status: "Al-Qur'an Lengkap", rewayaIds: "1,3,12,21,2", page: "https://www.mp3quran.net/id/dos", downloads: "https://www.mp3quran.net/id/dos/downloads" },
  { id: 44, name: "Idris akbar", slug: "idr", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/idr", downloads: "https://www.mp3quran.net/id/idr/downloads" },
  { id: 45, name: "Ismail annabi", slug: "annabi", status: "7 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/annabi", downloads: "https://www.mp3quran.net/id/annabi/downloads" },
  { id: 46, name: "Jasser ad dusariy", slug: "jasser", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/jasser", downloads: "https://www.mp3quran.net/id/jasser/downloads" },
  { id: 47, name: "Kamel ahmed hafi", slug: "kamel", status: "14 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/kamel", downloads: "https://www.mp3quran.net/id/kamel/downloads" },
  { id: 48, name: "Khalid abdulkafy", slug: "abd_kafi", status: "Al-Qur'an Lengkap", rewayaIds: "2,8,1", page: "https://www.mp3quran.net/id/abd_kafi", downloads: "https://www.mp3quran.net/id/abd_kafi/downloads" },
  { id: 49, name: "Khalid al jalil", slug: "jaleel", status: "Al-Qur'an Lengkap", rewayaIds: "1,21", page: "https://www.mp3quran.net/id/jaleel", downloads: "https://www.mp3quran.net/id/jaleel/downloads" },
  { id: 50, name: "Khalid al qahtani", slug: "khalid-alqahtani", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/khalid-alqahtani", downloads: "https://www.mp3quran.net/id/khalid-alqahtani/downloads" },
  { id: 51, name: "Khalid al qahtany", slug: "khtny", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/khtny", downloads: "https://www.mp3quran.net/id/khtny/downloads" },
  { id: 52, name: "Maher al meaqily", slug: "maa", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/maa", downloads: "https://www.mp3quran.net/id/maa/downloads" },
  { id: 53, name: "Mahmood saud", slug: "mahmoud-ali", status: "19 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/mahmoud-ali", downloads: "https://www.mp3quran.net/id/mahmoud-ali/downloads" },
  { id: 54, name: "Mahmud ali al banna", slug: "bna", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2", page: "https://www.mp3quran.net/id/bna", downloads: "https://www.mp3quran.net/id/bna/downloads" },
  { id: 55, name: "Majid al zamil", slug: "zamil", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/zamil", downloads: "https://www.mp3quran.net/id/zamil/downloads" },
  { id: 56, name: "Mohammad allohebi", slug: "alhaidan", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/alhaidan", downloads: "https://www.mp3quran.net/id/alhaidan/downloads" },
  { id: 57, name: "Mohammad al tablawiy", slug: "tbl", status: "Al-Qur'an Lengkap", rewayaIds: "22,1", page: "https://www.mp3quran.net/id/tbl", downloads: "https://www.mp3quran.net/id/tbl/downloads" },
  { id: 58, name: "Mohammad bin abd al kareem", slug: "mohammad-ibn-abd-al-kareem", status: "18 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/mohammad-ibn-abd-al-kareem", downloads: "https://www.mp3quran.net/id/mohammad-ibn-abd-al-kareem/downloads" },
  { id: 59, name: "Mohammed ayyub", slug: "ayyub", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ayyub", downloads: "https://www.mp3quran.net/id/ayyub/downloads" },
  { id: 60, name: "Mohammed jibraeel", slug: "mohammad-jibreel", status: "Al-Qur'an Lengkap", rewayaIds: "1,22", page: "https://www.mp3quran.net/id/mohammad-jibreel", downloads: "https://www.mp3quran.net/id/mohammad-jibreel/downloads" },
  { id: 61, name: "Mohamed layithy", slug: "lythee", status: "20 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/lythee", downloads: "https://www.mp3quran.net/id/lythee/downloads" },
  { id: 62, name: "Mohamed saleh aabed", slug: "abed", status: "10 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/abed", downloads: "https://www.mp3quran.net/id/abed/downloads" },
  { id: 63, name: "Muhammad hassan", slug: "hassan", status: "18 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/hassan", downloads: "https://www.mp3quran.net/id/hassan/downloads" },
  { id: 64, name: "Muhammad salah", slug: "muhammad-salah", status: "18 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/muhammad-salah", downloads: "https://www.mp3quran.net/id/muhammad-salah/downloads" },
  { id: 65, name: "Mustafa al laahony", slug: "lahoni", status: "Al-Qur'an Lengkap", rewayaIds: "22,1,8", page: "https://www.mp3quran.net/id/lahoni", downloads: "https://www.mp3quran.net/id/lahoni/downloads" },
  { id: 66, name: "Mustafa ismail", slug: "mostafa_ismaeel", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,21", page: "https://www.mp3quran.net/id/mostafa_ismaeel", downloads: "https://www.mp3quran.net/id/mostafa_ismaeel/downloads" },
  { id: 67, name: "Mustafa raad al azawi", slug: "azawy", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/azawy", downloads: "https://www.mp3quran.net/id/azawy/downloads" },
  { id: 68, name: "Nabil ar rifai", slug: "nabil", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/nabil", downloads: "https://www.mp3quran.net/id/nabil/downloads" },
  { id: 69, name: "Nasser al qatamy", slug: "qatami", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/qatami", downloads: "https://www.mp3quran.net/id/qatami/downloads" },
  { id: 70, name: "Omar al kazabry", slug: "omar_alkazabry", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/omar_alkazabry", downloads: "https://www.mp3quran.net/id/omar_alkazabry/downloads" },
  { id: 71, name: "Raad mohammed al kurdi", slug: "raad-mohammad-alkurdi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/raad-mohammad-alkurdi", downloads: "https://www.mp3quran.net/id/raad-mohammad-alkurdi/downloads" },
  { id: 72, name: "Saad al ghamadi", slug: "gmd", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/gmd", downloads: "https://www.mp3quran.net/id/gmd/downloads" },
  { id: 73, name: "Salah al budair", slug: "budair", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/budair", downloads: "https://www.mp3quran.net/id/budair/downloads" },
  { id: 74, name: "Salah bukhatir", slug: "bukhatir", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/bukhatir", downloads: "https://www.mp3quran.net/id/bukhatir/downloads" },
  { id: 75, name: "Saleh al humaid", slug: "homaid", status: "16 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/homaid", downloads: "https://www.mp3quran.net/id/homaid/downloads" },
  { id: 76, name: "Salman al utaybi", slug: "salman", status: "18 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/salman", downloads: "https://www.mp3quran.net/id/salman/downloads" },
  { id: 77, name: "Saud ash shuraim", slug: "saood", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/saood", downloads: "https://www.mp3quran.net/id/saood/downloads" },
  { id: 78, name: "Sayyid ramadan", slug: "sayyed-ramadan", status: "14 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/sayyed-ramadan", downloads: "https://www.mp3quran.net/id/sayyed-ramadan/downloads" },
  { id: 79, name: "Shaikh abu bakr asy syathiriy", slug: "shaatree", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/shaatree", downloads: "https://www.mp3quran.net/id/shaatree/downloads" },
  { id: 80, name: "Shuraym", slug: "shrem", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/shrem", downloads: "https://www.mp3quran.net/id/shrem/downloads" },
  { id: 81, name: "Taha al junaid", slug: "taha", status: "13 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/taha", downloads: "https://www.mp3quran.net/id/taha/downloads" },
  { id: 82, name: "Wadi al yemeni", slug: "wadi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/wadi", downloads: "https://www.mp3quran.net/id/wadi/downloads" },
  { id: 83, name: "Walid nasar", slug: "waleed-nasr", status: "11 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/waleed-nasr", downloads: "https://www.mp3quran.net/id/waleed-nasr/downloads" },
  { id: 84, name: "Yaser salama", slug: "yasser-salamah", status: "Al-Qur'an Lengkap", rewayaIds: "2,22,1", page: "https://www.mp3quran.net/id/yasser-salamah", downloads: "https://www.mp3quran.net/id/yasser-salamah/downloads" },
  { id: 85, name: "Yasser ad dussary", slug: "dosri", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/dosri", downloads: "https://www.mp3quran.net/id/dosri/downloads" },
  { id: 86, name: "Youssef edress al saidawy", slug: "edrees", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/edrees", downloads: "https://www.mp3quran.net/id/edrees/downloads" },
  { id: 87, name: "Zaki daghistani", slug: "zaki", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/zaki", downloads: "https://www.mp3quran.net/id/zaki/downloads" },
  { id: 88, name: "Abdullah abd al gany", slug: "aagny", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/aagny", downloads: "https://www.mp3quran.net/id/aagny/downloads" },
  { id: 89, name: "Abdullah al buajy", slug: "buajy", status: "13 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/buajy", downloads: "https://www.mp3quran.net/id/buajy/downloads" },
  { id: 90, name: "Abdullah al kandery", slug: "alkanderi", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/alkanderi", downloads: "https://www.mp3quran.net/id/alkanderi/downloads" },
  { id: 91, name: "Abdullah al mousa", slug: "abdallah-almousa", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdallah-almousa", downloads: "https://www.mp3quran.net/id/abdallah-almousa/downloads" },
  { id: 92, name: "Abdullah basfar", slug: "basfar", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/basfar", downloads: "https://www.mp3quran.net/id/basfar/downloads" },
  { id: 93, name: "Abdullah matrood", slug: "matroud", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/matroud", downloads: "https://www.mp3quran.net/id/matroud/downloads" },
  { id: 94, name: "Abdulrahman al osy", slug: "osi", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/osi", downloads: "https://www.mp3quran.net/id/osi/downloads" },
  { id: 95, name: "Abu bakr al shatri", slug: "shatry", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/shatry", downloads: "https://www.mp3quran.net/id/shatry/downloads" },
  { id: 96, name: "Ahmad al hawashi", slug: "hawashy", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/hawashy", downloads: "https://www.mp3quran.net/id/hawashy/downloads" },
  { id: 97, name: "Ahmad bin ali al ajamy", slug: "ajamy", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/ajamy", downloads: "https://www.mp3quran.net/id/ajamy/downloads" },
  { id: 98, name: "Ahmad saud", slug: "ahmad_saud", status: "5 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/ahmad_saud", downloads: "https://www.mp3quran.net/id/ahmad_saud/downloads" },
  { id: 99, name: "Ahmed al nufays", slug: "nufais", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/nufais", downloads: "https://www.mp3quran.net/id/nufais/downloads" },
  { id: 100, name: "Akram al alaqmy", slug: "alaqimy", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/alaqimy", downloads: "https://www.mp3quran.net/id/alaqimy/downloads" },
  { id: 101, name: "Alafasy", slug: "alafasy", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/alafasy", downloads: "https://www.mp3quran.net/id/alafasy/downloads" },
  { id: 102, name: "Ali al hajary", slug: "ali_hajjaj", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/ali_hajjaj", downloads: "https://www.mp3quran.net/id/ali_hajjaj/downloads" },
  { id: 103, name: "Aziz alili", slug: "aziz_alili", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/aziz_alili", downloads: "https://www.mp3quran.net/id/aziz_alili/downloads" },
  { id: 104, name: "Bandar baleelah", slug: "baleelah", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/baleelah", downloads: "https://www.mp3quran.net/id/baleelah/downloads" },
  { id: 105, name: "Emad al mansary", slug: "emad", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/emad", downloads: "https://www.mp3quran.net/id/emad/downloads" },
  { id: 106, name: "Fares abbad", slug: "fares", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/fares", downloads: "https://www.mp3quran.net/id/fares/downloads" },
  { id: 107, name: "Hajjaj al hindawi", slug: "hajjaj", status: "11 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/hajjaj", downloads: "https://www.mp3quran.net/id/hajjaj/downloads" },
  { id: 108, name: "Hamad sinan", slug: "sinan", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/sinan", downloads: "https://www.mp3quran.net/id/sinan/downloads" },
  { id: 109, name: "Hatem farid", slug: "hatem", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/hatem", downloads: "https://www.mp3quran.net/id/hatem/downloads" },
  { id: 110, name: "Husayn al shaykh", slug: "husayn", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/husayn", downloads: "https://www.mp3quran.net/id/husayn/downloads" },
  { id: 111, name: "Ibrahim al akhdar", slug: "akhdar", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2,8", page: "https://www.mp3quran.net/id/akhdar", downloads: "https://www.mp3quran.net/id/akhdar/downloads" },
  { id: 112, name: "Ibrahim al jibreen", slug: "jibreen", status: "8 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/jibreen", downloads: "https://www.mp3quran.net/id/jibreen/downloads" },
  { id: 113, name: "Ibrahim aldosary", slug: "aldosary", status: "Al-Qur'an Lengkap", rewayaIds: "1,3,12,21,2", page: "https://www.mp3quran.net/id/aldosary", downloads: "https://www.mp3quran.net/id/aldosary/downloads" },
  { id: 114, name: "Karim mansouri", slug: "mansouri", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/mansouri", downloads: "https://www.mp3quran.net/id/mansouri/downloads" },
  { id: 115, name: "Khalid al qahtani", slug: "qahtani", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/qahtani", downloads: "https://www.mp3quran.net/id/qahtani/downloads" },
  { id: 116, name: "Khalil al husary", slug: "husary", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2,13,5", page: "https://www.mp3quran.net/id/husary", downloads: "https://www.mp3quran.net/id/husary/downloads" },
  { id: 117, name: "Maher al muaiqly", slug: "muaiqly", status: "Al-Qur'an Lengkap", rewayaIds: "1,21,22", page: "https://www.mp3quran.net/id/muaiqly", downloads: "https://www.mp3quran.net/id/muaiqly/downloads" },
  { id: 118, name: "Mahmoud ali al banna", slug: "banna", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2", page: "https://www.mp3quran.net/id/banna", downloads: "https://www.mp3quran.net/id/banna/downloads" },
  { id: 119, name: "Majed al enezi", slug: "enezi", status: "11 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/enezi", downloads: "https://www.mp3quran.net/id/enezi/downloads" },
  { id: 120, name: "Majed al zamil", slug: "majed", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/majed", downloads: "https://www.mp3quran.net/id/majed/downloads" },
  { id: 121, name: "Mishary alafasy", slug: "mishary", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/mishary", downloads: "https://www.mp3quran.net/id/mishary/downloads" },
  { id: 122, name: "Mohammad al tablaway", slug: "tablaway", status: "Al-Qur'an Lengkap", rewayaIds: "22,1", page: "https://www.mp3quran.net/id/tablaway", downloads: "https://www.mp3quran.net/id/tablaway/downloads" },
  { id: 123, name: "Muhammad al meheisny", slug: "meheisny", status: "13 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/meheisny", downloads: "https://www.mp3quran.net/id/meheisny/downloads" },
  { id: 124, name: "Muhammad ayyub", slug: "mohammed_ayyoub", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/mohammed_ayyoub", downloads: "https://www.mp3quran.net/id/mohammed_ayyoub/downloads" },
  { id: 125, name: "Muhammad jibreel", slug: "jibreel", status: "Al-Qur'an Lengkap", rewayaIds: "1,22", page: "https://www.mp3quran.net/id/jibreel", downloads: "https://www.mp3quran.net/id/jibreel/downloads" },
  { id: 126, name: "Muhammad siddiq al minshawi", slug: "minshawi", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,21", page: "https://www.mp3quran.net/id/minshawi", downloads: "https://www.mp3quran.net/id/minshawi/downloads" },
  { id: 127, name: "Mustafa al azawi", slug: "mustafa", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/mustafa", downloads: "https://www.mp3quran.net/id/mustafa/downloads" },
  { id: 128, name: "Mustafa ismail", slug: "ismail", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,21", page: "https://www.mp3quran.net/id/ismail", downloads: "https://www.mp3quran.net/id/ismail/downloads" },
  { id: 129, name: "Mustafa laahoni", slug: "laahoni", status: "Al-Qur'an Lengkap", rewayaIds: "22,1,8", page: "https://www.mp3quran.net/id/laahoni", downloads: "https://www.mp3quran.net/id/laahoni/downloads" },
  { id: 130, name: "Nabil ar rifai", slug: "rifai", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/rifai", downloads: "https://www.mp3quran.net/id/rifai/downloads" },
  { id: 131, name: "Naser al qatami", slug: "naser_alqatami", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/naser_alqatami", downloads: "https://www.mp3quran.net/id/naser_alqatami/downloads" },
  { id: 132, name: "Raad al kurdi", slug: "raad", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/raad", downloads: "https://www.mp3quran.net/id/raad/downloads" },
  { id: 133, name: "Saad al ghamdi", slug: "saad_ghamdi", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/saad_ghamdi", downloads: "https://www.mp3quran.net/id/saad_ghamdi/downloads" },
  { id: 134, name: "Salah al budair", slug: "salah_budair", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/salah_budair", downloads: "https://www.mp3quran.net/id/salah_budair/downloads" },
  { id: 135, name: "Salah bukhatir", slug: "salah_bukhatir", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/salah_bukhatir", downloads: "https://www.mp3quran.net/id/salah_bukhatir/downloads" },
  { id: 136, name: "Saud al shuraim", slug: "saud_shuraim", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/saud_shuraim", downloads: "https://www.mp3quran.net/id/saud_shuraim/downloads" },
  { id: 137, name: "Tawfeeq as sayegh", slug: "sayegh", status: "Al-Qur'an Lengkap", rewayaIds: "1,2", page: "https://www.mp3quran.net/id/sayegh", downloads: "https://www.mp3quran.net/id/sayegh/downloads" },
  { id: 138, name: "Wadi al yamani", slug: "yamani", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/yamani", downloads: "https://www.mp3quran.net/id/yamani/downloads" },
  { id: 139, name: "Yaser ad dussary", slug: "yaser_dussary", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/yaser_dussary", downloads: "https://www.mp3quran.net/id/yaser_dussary/downloads" },
  { id: 140, name: "Yasser salama", slug: "salama", status: "Al-Qur'an Lengkap", rewayaIds: "2,22,1", page: "https://www.mp3quran.net/id/salama", downloads: "https://www.mp3quran.net/id/salama/downloads" },
  { id: 141, name: "Youssef edris alsaidawi", slug: "saidawi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/saidawi", downloads: "https://www.mp3quran.net/id/saidawi/downloads" },
  { id: 142, name: "Abdul basit murattal", slug: "abdul_basit_murattal", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2", page: "https://www.mp3quran.net/id/abdul_basit_murattal", downloads: "https://www.mp3quran.net/id/abdul_basit_murattal/downloads" },
  { id: 143, name: "Abdul rahman al sudais", slug: "abdul_rahman_sudais", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdul_rahman_sudais", downloads: "https://www.mp3quran.net/id/abdul_rahman_sudais/downloads" },
  { id: 144, name: "Abdullah awwad al juhani", slug: "juhani", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/juhani", downloads: "https://www.mp3quran.net/id/juhani/downloads" },
  { id: 145, name: "Abdullah basfer", slug: "abdullah_basfer", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/abdullah_basfer", downloads: "https://www.mp3quran.net/id/abdullah_basfer/downloads" },
  { id: 146, name: "Abdullah kamil", slug: "abdullah_kamil", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdullah_kamil", downloads: "https://www.mp3quran.net/id/abdullah_kamil/downloads" },
  { id: 147, name: "Abdullah matroud", slug: "abdullah_matroud", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdullah_matroud", downloads: "https://www.mp3quran.net/id/abdullah_matroud/downloads" },
  { id: 148, name: "Abdulmohsen al qasim", slug: "abdulmohsen", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdulmohsen", downloads: "https://www.mp3quran.net/id/abdulmohsen/downloads" },
  { id: 149, name: "Abdulrahman al ossi", slug: "ossi", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ossi", downloads: "https://www.mp3quran.net/id/ossi/downloads" },
  { id: 150, name: "Abdulwadud haneef", slug: "abdulwadud", status: "15 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdulwadud", downloads: "https://www.mp3quran.net/id/abdulwadud/downloads" },
  { id: 151, name: "Abu bakr shatri", slug: "abu_bakr_shatri", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/abu_bakr_shatri", downloads: "https://www.mp3quran.net/id/abu_bakr_shatri/downloads" },
  { id: 152, name: "Ahmad al ajmi", slug: "ahmad_ajmi", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/ahmad_ajmi", downloads: "https://www.mp3quran.net/id/ahmad_ajmi/downloads" },
  { id: 153, name: "Ahmad khader al tarabulsi", slug: "tarabulsi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/tarabulsi", downloads: "https://www.mp3quran.net/id/tarabulsi/downloads" },
  { id: 154, name: "Ahmed al hawashy", slug: "ahmed_hawashy", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ahmed_hawashy", downloads: "https://www.mp3quran.net/id/ahmed_hawashy/downloads" },
  { id: 155, name: "Ahmed ibn ali al ajamy", slug: "ahmed_ajamy", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/ahmed_ajamy", downloads: "https://www.mp3quran.net/id/ahmed_ajamy/downloads" },
  { id: 156, name: "Ahmed naina", slug: "ahmed_naina", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/ahmed_naina", downloads: "https://www.mp3quran.net/id/ahmed_naina/downloads" },
  { id: 157, name: "Ali abd ar rahman al huthaify", slug: "ali_huthaify", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ali_huthaify", downloads: "https://www.mp3quran.net/id/ali_huthaify/downloads" },
  { id: 158, name: "Ali al hajjaj al souissy", slug: "ali_souissy", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/ali_souissy", downloads: "https://www.mp3quran.net/id/ali_souissy/downloads" },
  { id: 159, name: "Ali jaber", slug: "ali_jaber", status: "Al-Qur'an Lengkap", rewayaIds: "1,2", page: "https://www.mp3quran.net/id/ali_jaber", downloads: "https://www.mp3quran.net/id/ali_jaber/downloads" },
  { id: 160, name: "Aziz alili", slug: "aziz", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/aziz", downloads: "https://www.mp3quran.net/id/aziz/downloads" },
  { id: 161, name: "Emad al mansari", slug: "mansari", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/mansari", downloads: "https://www.mp3quran.net/id/mansari/downloads" },
  { id: 162, name: "Fahad al kandari", slug: "fahad", status: "17 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/fahad", downloads: "https://www.mp3quran.net/id/fahad/downloads" },
  { id: 163, name: "Fares abbad", slug: "fares_abbad", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/fares_abbad", downloads: "https://www.mp3quran.net/id/fares_abbad/downloads" },
  { id: 164, name: "Hani ar rifai", slug: "hani_rifai", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/hani_rifai", downloads: "https://www.mp3quran.net/id/hani_rifai/downloads" },
  { id: 165, name: "Hatem farid", slug: "hatem_farid", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/hatem_farid", downloads: "https://www.mp3quran.net/id/hatem_farid/downloads" },
  { id: 166, name: "Ibrahim al dosari", slug: "ibrahim_dosari", status: "Al-Qur'an Lengkap", rewayaIds: "1,3,12,21,2", page: "https://www.mp3quran.net/id/ibrahim_dosari", downloads: "https://www.mp3quran.net/id/ibrahim_dosari/downloads" },
  { id: 167, name: "Ibrahim emeer", slug: "emeer", status: "13 Surah", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/emeer", downloads: "https://www.mp3quran.net/id/emeer/downloads" },
  { id: 168, name: "Idris abkar", slug: "idris", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/idris", downloads: "https://www.mp3quran.net/id/idris/downloads" },
  { id: 169, name: "Jasser al dosari", slug: "jasser_dosari", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/jasser_dosari", downloads: "https://www.mp3quran.net/id/jasser_dosari/downloads" },
  { id: 170, name: "Khalid al jalil", slug: "khalid_jalil", status: "Al-Qur'an Lengkap", rewayaIds: "1,21", page: "https://www.mp3quran.net/id/khalid_jalil", downloads: "https://www.mp3quran.net/id/khalid_jalil/downloads" },
  { id: 171, name: "Khalid al qahtani", slug: "khalid_qahtani", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/khalid_qahtani", downloads: "https://www.mp3quran.net/id/khalid_qahtani/downloads" },
  { id: 172, name: "Khalid bin abdulkafi", slug: "khalid_abdulkafi", status: "Al-Qur'an Lengkap", rewayaIds: "2,8,1", page: "https://www.mp3quran.net/id/khalid_abdulkafi", downloads: "https://www.mp3quran.net/id/khalid_abdulkafi/downloads" },
  { id: 173, name: "Mahmoud al husary", slug: "mahmoud_husary", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2,13,5", page: "https://www.mp3quran.net/id/mahmoud_husary", downloads: "https://www.mp3quran.net/id/mahmoud_husary/downloads" },
  { id: 174, name: "Mahmoud khalil al hussary mujawwad", slug: "hussary_mujawwad", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/hussary_mujawwad", downloads: "https://www.mp3quran.net/id/hussary_mujawwad/downloads" },
  { id: 175, name: "Mazen al rayyan", slug: "rayyan", status: "7 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/rayyan", downloads: "https://www.mp3quran.net/id/rayyan/downloads" },
  { id: 176, name: "Mohamed al mohisni", slug: "mohisni", status: "13 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/mohisni", downloads: "https://www.mp3quran.net/id/mohisni/downloads" },
  { id: 177, name: "Mohamed el-hadidi", slug: "hadidi", status: "14 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/hadidi", downloads: "https://www.mp3quran.net/id/hadidi/downloads" },
  { id: 178, name: "Mohamed layithy", slug: "layithy", status: "20 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/layithy", downloads: "https://www.mp3quran.net/id/layithy/downloads" },
  { id: 179, name: "Mohammad al luhaidan", slug: "luhaidan", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/luhaidan", downloads: "https://www.mp3quran.net/id/luhaidan/downloads" },
  { id: 180, name: "Mohammad al tablawi", slug: "mohammad_tablawi", status: "Al-Qur'an Lengkap", rewayaIds: "22,1", page: "https://www.mp3quran.net/id/mohammad_tablawi", downloads: "https://www.mp3quran.net/id/mohammad_tablawi/downloads" },
  { id: 181, name: "Mohammed ayyoub", slug: "ayyoub", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ayyoub", downloads: "https://www.mp3quran.net/id/ayyoub/downloads" },
  { id: 182, name: "Mohammed jibreel", slug: "mohammed_jibreel", status: "Al-Qur'an Lengkap", rewayaIds: "1,22", page: "https://www.mp3quran.net/id/mohammed_jibreel", downloads: "https://www.mp3quran.net/id/mohammed_jibreel/downloads" },
  { id: 183, name: "Mousa bilal", slug: "mousa", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/mousa", downloads: "https://www.mp3quran.net/id/mousa/downloads" },
  { id: 184, name: "Muhammad abdulkarim", slug: "abdulkarim", status: "18 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdulkarim", downloads: "https://www.mp3quran.net/id/abdulkarim/downloads" },
  { id: 185, name: "Muhammad al minshawi", slug: "muhammad_minshawi", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,21", page: "https://www.mp3quran.net/id/muhammad_minshawi", downloads: "https://www.mp3quran.net/id/muhammad_minshawi/downloads" },
  { id: 186, name: "Mustafa al azawi", slug: "mustafa_azawi", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/mustafa_azawi", downloads: "https://www.mp3quran.net/id/mustafa_azawi/downloads" },
  { id: 187, name: "Mustafa al lahoni", slug: "mustafa_lahoni", status: "Al-Qur'an Lengkap", rewayaIds: "22,1,8", page: "https://www.mp3quran.net/id/mustafa_lahoni", downloads: "https://www.mp3quran.net/id/mustafa_lahoni/downloads" },
  { id: 188, name: "Mustafa ismail", slug: "mustafa_ismail", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,21", page: "https://www.mp3quran.net/id/mustafa_ismail", downloads: "https://www.mp3quran.net/id/mustafa_ismail/downloads" },
  { id: 189, name: "Nabil ar rifai", slug: "nabil_rifai", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/nabil_rifai", downloads: "https://www.mp3quran.net/id/nabil_rifai/downloads" },
  { id: 190, name: "Nasser al qatami", slug: "nasser_qatami", status: "Al-Qur'an Lengkap", rewayaIds: "1,12", page: "https://www.mp3quran.net/id/nasser_qatami", downloads: "https://www.mp3quran.net/id/nasser_qatami/downloads" },
  { id: 191, name: "Omar al kazabri", slug: "omar_kazabri", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/omar_kazabri", downloads: "https://www.mp3quran.net/id/omar_kazabri/downloads" },
  { id: 192, name: "Raad al kurdi", slug: "raad_kurdi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/raad_kurdi", downloads: "https://www.mp3quran.net/id/raad_kurdi/downloads" },
  { id: 193, name: "Rashid belasheyyah", slug: "belasheyyah", status: "17 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/belasheyyah", downloads: "https://www.mp3quran.net/id/belasheyyah/downloads" },
  { id: 194, name: "Saad el ghamadi", slug: "saad_ghamadi", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/saad_ghamadi", downloads: "https://www.mp3quran.net/id/saad_ghamadi/downloads" },
  { id: 195, name: "Saeed al harby", slug: "harby", status: "14 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/harby", downloads: "https://www.mp3quran.net/id/harby/downloads" },
  { id: 196, name: "Salah al budair", slug: "salah_al_budair", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/salah_al_budair", downloads: "https://www.mp3quran.net/id/salah_al_budair/downloads" },
  { id: 197, name: "Salah bo khater", slug: "salah_bo_khater", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/salah_bo_khater", downloads: "https://www.mp3quran.net/id/salah_bo_khater/downloads" },
  { id: 198, name: "Saleh al humaid", slug: "saleh_humaid", status: "16 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/saleh_humaid", downloads: "https://www.mp3quran.net/id/saleh_humaid/downloads" },
  { id: 199, name: "Salman al utaybi", slug: "salman_utaybi", status: "18 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/salman_utaybi", downloads: "https://www.mp3quran.net/id/salman_utaybi/downloads" },
  { id: 200, name: "Saud al shuraim", slug: "saud_al_shuraim", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/saud_al_shuraim", downloads: "https://www.mp3quran.net/id/saud_al_shuraim/downloads" },
  { id: 201, name: "Shuraim", slug: "shuraim", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/shuraim", downloads: "https://www.mp3quran.net/id/shuraim/downloads" },
  { id: 202, name: "Taha al junaid", slug: "taha_junaid", status: "13 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/taha_junaid", downloads: "https://www.mp3quran.net/id/taha_junaid/downloads" },
  { id: 203, name: "Tawfeeq as sayegh", slug: "tawfeeq_sayegh", status: "Al-Qur'an Lengkap", rewayaIds: "1,2", page: "https://www.mp3quran.net/id/tawfeeq_sayegh", downloads: "https://www.mp3quran.net/id/tawfeeq_sayegh/downloads" },
  { id: 204, name: "Wadi al yamani", slug: "wadi_yamani", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/wadi_yamani", downloads: "https://www.mp3quran.net/id/wadi_yamani/downloads" },
  { id: 205, name: "Wadih al yamani", slug: "wadih", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/wadih", downloads: "https://www.mp3quran.net/id/wadih/downloads" },
  { id: 206, name: "Waleed idrees al meneese", slug: "meneese", status: "18 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/meneese", downloads: "https://www.mp3quran.net/id/meneese/downloads" },
  { id: 207, name: "Yaser al dosari", slug: "yaser_dosari", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/yaser_dosari", downloads: "https://www.mp3quran.net/id/yaser_dosari/downloads" },
  { id: 208, name: "Yasser salama", slug: "yasser_salama", status: "Al-Qur'an Lengkap", rewayaIds: "2,22,1", page: "https://www.mp3quran.net/id/yasser_salama", downloads: "https://www.mp3quran.net/id/yasser_salama/downloads" },
  { id: 209, name: "Youssef edris alsaidawi", slug: "youssef_saidawi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/youssef_saidawi", downloads: "https://www.mp3quran.net/id/youssef_saidawi/downloads" },
  { id: 210, name: "Zaki daghistani", slug: "zaki_daghistani", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/zaki_daghistani", downloads: "https://www.mp3quran.net/id/zaki_daghistani/downloads" },
  { id: 211, name: "Abdul azim zahid", slug: "zahid", status: "12 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/zahid", downloads: "https://www.mp3quran.net/id/zahid/downloads" },
  { id: 212, name: "Abdul rahman al ussi", slug: "ussi", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ussi", downloads: "https://www.mp3quran.net/id/ussi/downloads" },
  { id: 213, name: "Abdulaziz al ahmad", slug: "ahmad_az", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ahmad_az", downloads: "https://www.mp3quran.net/id/ahmad_az/downloads" },
  { id: 214, name: "Abdullah ali jaber", slug: "abdullah_jaber", status: "14 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/abdullah_jaber", downloads: "https://www.mp3quran.net/id/abdullah_jaber/downloads" },
  { id: 215, name: "Abdulrahman al ausy", slug: "ausy", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ausy", downloads: "https://www.mp3quran.net/id/ausy/downloads" },
  { id: 216, name: "Ahmad al nufays", slug: "ahmad_nufays", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ahmad_nufays", downloads: "https://www.mp3quran.net/id/ahmad_nufays/downloads" },
  { id: 217, name: "Ahmad khader tarabulsi", slug: "ahmad_tarabulsi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/ahmad_tarabulsi", downloads: "https://www.mp3quran.net/id/ahmad_tarabulsi/downloads" },
  { id: 218, name: "Ahmed al nufais", slug: "ahmed_nufais", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ahmed_nufais", downloads: "https://www.mp3quran.net/id/ahmed_nufais/downloads" },
  { id: 219, name: "Ali bin abdurrahman al huthaifi", slug: "ali_abdurrahman", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ali_abdurrahman", downloads: "https://www.mp3quran.net/id/ali_abdurrahman/downloads" },
  { id: 220, name: "Faisal al suwaid", slug: "faisal", status: "8 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/faisal", downloads: "https://www.mp3quran.net/id/faisal/downloads" },
  { id: 221, name: "Hassan saleh", slug: "hassan_saleh", status: "18 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/hassan_saleh", downloads: "https://www.mp3quran.net/id/hassan_saleh/downloads" },
  { id: 222, name: "Ibrahim al jibreen", slug: "ibrahim_jibreen", status: "8 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/ibrahim_jibreen", downloads: "https://www.mp3quran.net/id/ibrahim_jibreen/downloads" },
  { id: 223, name: "Khalid abdullah", slug: "khalid_abdullah", status: "13 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/khalid_abdullah", downloads: "https://www.mp3quran.net/id/khalid_abdullah/downloads" },
  { id: 224, name: "Mahmud al husary", slug: "mahmud_husary", status: "Al-Qur'an Lengkap", rewayaIds: "1,22,2,13,5", page: "https://www.mp3quran.net/id/mahmud_husary", downloads: "https://www.mp3quran.net/id/mahmud_husary/downloads" },
  { id: 225, name: "Majed al enazi", slug: "majed_enazi", status: "11 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/majed_enazi", downloads: "https://www.mp3quran.net/id/majed_enazi/downloads" },
  { id: 226, name: "Mohamed el hadidy", slug: "mohamed_hadidy", status: "14 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/mohamed_hadidy", downloads: "https://www.mp3quran.net/id/mohamed_hadidy/downloads" },
  { id: 227, name: "Mohamed saleh", slug: "mohamed_saleh", status: "18 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/mohamed_saleh", downloads: "https://www.mp3quran.net/id/mohamed_saleh/downloads" },
  { id: 228, name: "Mohammad al kurdi", slug: "mohammad_kurdi", status: "Al-Qur'an Lengkap", rewayaIds: "2,1", page: "https://www.mp3quran.net/id/mohammad_kurdi", downloads: "https://www.mp3quran.net/id/mohammad_kurdi/downloads" },
  { id: 229, name: "Rashid al afasy", slug: "rashid_afasy", status: "18 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/rashid_afasy", downloads: "https://www.mp3quran.net/id/rashid_afasy/downloads" },
  { id: 230, name: "Salah al hashim", slug: "hashim", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/hashim", downloads: "https://www.mp3quran.net/id/hashim/downloads" },
  { id: 231, name: "Sayyid ramadhan", slug: "sayyid_ramadhan", status: "14 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/sayyid_ramadhan", downloads: "https://www.mp3quran.net/id/sayyid_ramadhan/downloads" },
  { id: 232, name: "Turki al mutlaq", slug: "mutlaq", status: "7 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/mutlaq", downloads: "https://www.mp3quran.net/id/mutlaq/downloads" },
  { id: 233, name: "Waleed abdullah al maneese", slug: "waleed_maneese", status: "18 Surah", rewayaIds: "1", page: "https://www.mp3quran.net/id/waleed_maneese", downloads: "https://www.mp3quran.net/id/waleed_maneese/downloads" },
  { id: 234, name: "Waleed nasr", slug: "waleed_nasr", status: "11 Surah", rewayaIds: "2", page: "https://www.mp3quran.net/id/waleed_nasr", downloads: "https://www.mp3quran.net/id/waleed_nasr/downloads" },
  { id: 235, name: "Yasir ad dussary", slug: "yasir_dussary", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/yasir_dussary", downloads: "https://www.mp3quran.net/id/yasir_dussary/downloads" },
  { id: 236, name: "Youssef bin noah ahmad", slug: "youssef_noah", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/youssef_noah", downloads: "https://www.mp3quran.net/id/youssef_noah/downloads" },
  { id: 237, name: "Zaki bin muhammad daghistani", slug: "zaki_mohammad", status: "Al-Qur'an Lengkap", rewayaIds: "2", page: "https://www.mp3quran.net/id/zaki_mohammad", downloads: "https://www.mp3quran.net/id/zaki_mohammad/downloads" },
  { id: 238, name: "Ibrahim al akhdar mujawwad", slug: "akhdar_mujawwad", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/akhdar_mujawwad", downloads: "https://www.mp3quran.net/id/akhdar_mujawwad/downloads" },
  { id: 239, name: "Ayman suwaid", slug: "ayman_suwaid", status: "Al-Qur'an Lengkap", rewayaIds: "1", page: "https://www.mp3quran.net/id/ayman_suwaid", downloads: "https://www.mp3quran.net/id/ayman_suwaid/downloads" }
];

export function searchMurotal(query: string): Qari[] {
  if (!query || query.trim() === '') {
    return MUROTAL_LIST.slice(0, 20); // Return first 20 if no search
  }

  const lowerQuery = query.toLowerCase();
  return MUROTAL_LIST.filter(qari => 
    qari.name.toLowerCase().includes(lowerQuery) ||
    qari.slug.toLowerCase().includes(lowerQuery)
  );
}

export function getMurotalById(id: number): Qari | undefined {
  return MUROTAL_LIST.find(qari => qari.id === id);
}

export function getAllMurotal(): Qari[] {
  return MUROTAL_LIST;
}
